# Generated by Django 4.1.7 on 2023-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userpayments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=25)),
                ('phone', models.IntegerField()),
                ('cart', models.BooleanField(default=False)),
                ('wishlist', models.BooleanField(default=False)),
                ('product_name', models.CharField(max_length=999)),
                ('address', models.CharField(max_length=999)),
                ('product_category', models.CharField(max_length=999)),
                ('product_id', models.IntegerField()),
                ('available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('paymentid', models.CharField(default='False', max_length=99)),
                ('paymentstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
