# Generated by Django 4.1.7 on 2023-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayments',
            name='payment_stamp',
        ),
        migrations.AddField(
            model_name='userpayments',
            name='cart',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
