# Generated by Django 4.1.7 on 2023-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_userpayments_address_remove_userpayments_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
