# Generated by Django 4.1.7 on 2023-03-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_userpayments_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='cart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userpayments',
            name='wishlist',
            field=models.IntegerField(default=0),
        ),
    ]
