# Generated by Django 4.1.7 on 2023-03-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_userpayments_cart_userpayments_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpayments',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
