# Generated by Django 4.1.7 on 2023-03-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_userpayments_cart_alter_userpayments_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
