# Generated by Django 4.1.7 on 2023-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_userpayments_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
