# Generated by Django 4.1.7 on 2023-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_userpayments_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpayments',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userpayments',
            name='product_category',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='userpayments',
            name='product_name',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='userpayments',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
