# Generated by Django 4.1.7 on 2023-03-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_userpayments_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='address',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpayments',
            name='available',
            field=models.IntegerField(),
        ),
    ]
