# Generated by Django 4.1.7 on 2023-03-25 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_userpayments_address_alter_userpayments_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='available',
            new_name='cartavailable',
        ),
    ]
