# Generated by Django 4.1.7 on 2023-03-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_rename_available_userpayments_cartavailable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayments',
            old_name='cartavailable',
            new_name='available',
        ),
        migrations.AddField(
            model_name='userpayments',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayments',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpayments',
            name='tax',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
