# Generated by Django 4.1.7 on 2023-04-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_rename_cartavailable_userpayments_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
