# Generated by Django 4.1.7 on 2023-04-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_userpayments_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
