# Generated by Django 4.1.7 on 2023-04-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_userpayments_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayments',
            name='confirm',
        ),
    ]
