# Generated by Django 4.1.7 on 2023-04-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_remove_userpayments_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayments',
            name='paymentid',
            field=models.IntegerField(default=0),
        ),
    ]
