# Generated by Django 4.1.7 on 2023-04-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_userpayments_paymentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayments',
            name='paymentid',
            field=models.CharField(default='False', max_length=99),
        ),
    ]
