# Generated by Django 4.1.7 on 2023-05-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carasouelimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='carasouel_image')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='productimg')),
                ('image2', models.ImageField(upload_to='productimg')),
                ('image3', models.ImageField(upload_to='productimg')),
                ('image4', models.ImageField(upload_to='productimg')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('tax', models.IntegerField()),
                ('size', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('available', models.IntegerField()),
                ('offer', models.BooleanField(default=True)),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
