# Generated by Django 4.1.7 on 2023-04-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_carasouelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carasouelimage',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
